services:
  gateway-web:
    image: ${DOCKER_REGISTRY-}web-gateway
    build:
      context: .
      dockerfile: Gateways/Web/Gateway.Web/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      shopeefood-clone-net:
        
  event-bus:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      shopeefood-clone-net:
        
  identity-api:
    image: ${DOCKER_REGISTRY-}identity-api
    build:
      context: .
      dockerfile: Services/Identity/Identity.Presentation/Dockerfile
    ports:
      - "5010:5010"
      - "5011:5011"
    depends_on:
      - users-db
    networks:
      shopeefood-clone-net:
        
  stores-api:
    image: ${DOCKER_REGISTRY-}stores-api
    build:
      context: .
      dockerfile: Services/Stores/Stores.Presentation/Dockerfile
    ports:
      - "5030:5030"
      - "5031:5031"
    depends_on:
      - stores-db
    networks:
      shopeefood-clone-net:
      
  cart-api:
    image: ${DOCKER_REGISTRY-}cart-api
    build:
      context: .
      dockerfile: Services/Cart/Cart.Presentation/Dockerfile
    ports:
      - "5050:5050"
      - "5051:5051"
    depends_on:
      - cart-db
    networks:
      shopeefood-clone-net:
        
  orders-api:
    image: ${DOCKER_REGISTRY-}orders-api
    build:
      context: .
      dockerfile: Services/Orders/Orders.Presentation/Dockerfile
    ports:
      - "5060:5060"
      - "5061:5061"
    depends_on:
      - orders-db
    networks:
      shopeefood-clone-net:
        
  products-api:
    image: ${DOCKER_REGISTRY-}products-api
    build:
      context: .
      dockerfile: Services/Products/Products.Presentation/Dockerfile
    ports:
      - "5040:5040"
      - "5041:5041"
    depends_on:
      - products-db
    networks:
      shopeefood-clone-net:
        
  payment-api:
    image: ${DOCKER_REGISTRY-}products-api
    build:
      context: .
      dockerfile: Services/Payment/Payment.Presentation/Dockerfile
    ports:
      - "5070:5070"
      - "5071:5071"
    depends_on:
      - payment-db
    networks:
      shopeefood-clone-net:
        
  users-api:
    image: ${DOCKER_REGISTRY-}users-api
    build:
      context: .
      dockerfile: Services/Users/Users.Presentation/Dockerfile
    ports:
      - "5020:5020"
      - "5021:5021"
    depends_on:
      - users-db
    networks:
      shopeefood-clone-net:

  users-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "14331:1433"
    volumes:
      - users_data:/var/opt/mssql
    networks:
      shopeefood-clone-net:
    restart: unless-stopped
    
  stores-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "14333:1433"
    volumes:
      - stores_data:/var/opt/mssql
    networks:
      shopeefood-clone-net:
    restart: unless-stopped
  
  cart-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "14335:1433"
    volumes:
      - cart_data:/var/opt/mssql
    networks:
      shopeefood-clone-net:
    restart: unless-stopped
    
  orders-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "14336:1433"
    volumes:
      - orders_data:/var/opt/mssql
    networks:
      shopeefood-clone-net:
    restart: unless-stopped
    
  products-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "14334:1433"
    volumes:
      - products_data:/var/opt/mssql
    networks:
      shopeefood-clone-net:
    restart: unless-stopped
    
  payment-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "14337:1433"
    volumes:
      - payment_data:/var/opt/mssql
    networks:
      shopeefood-clone-net:
    restart: unless-stopped

volumes:
  users_data:
  stores_data:
  products_data:
  cart_data:
  orders_data:
  payment_data:
    
networks:
  shopeefood-clone-net:
    driver: bridge
    external: true

