services:
  gateway-web:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5001;http://+:5000"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Gateway.Web.pfx"
    volumes:
      - ./certs/.aspnet/https/Gateway.Web.pfx:/home/app/.aspnet/https/Gateway.Web.pfx:ro
  
  identity-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5011;http://+:5010"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Identity.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Identity.API.pfx:/home/app/.aspnet/https/Identity.API.pfx:ro
  
  users-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5021;http://+:5020"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Users.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Users.API.pfx:/home/app/.aspnet/https/Users.API.pfx:ro
  
  stores-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5031;http://+:5030"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Stores.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Stores.API.pfx:/home/app/.aspnet/https/Stores.API.pfx:ro
    
  cart-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5051;http://+:5050"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Cart.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Cart.API.pfx:/home/app/.aspnet/https/Cart.API.pfx:ro
  
  orders-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5061;http://+:5060"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Orders.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Orders.API.pfx:/home/app/.aspnet/https/Orders.API.pfx:ro
  
  products-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5041;http://+:5040"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Products.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Products.API.pfx:/home/app/.aspnet/https/Products.API.pfx:ro
  
  payment-api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:5071;http://+:5070"
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${HTTPS_DEV_CERTS_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/home/app/.aspnet/https/Payment.API.pfx"
    volumes:
      - ./certs/.aspnet/https/Payment.API.pfx:/home/app/.aspnet/https/Payment.API.pfx:ro
